### ISSUE TITLE
GD32F103C8 support 

### ISSUE THREAD

**Issue by login55555** [max-bondarenko/cnc3018-offline-controller-marlin#1]
Hello
There are boards populated with STM32F103 substitute from GigaDevice 
https://www.gigadevice.com/product/mcu/arm-cortex-m3/gd32f103c8t6
It refuses to flash more than 65K
Is there any way to condense this code? Maybe by disabling some features?

**Comment by max-bondarenko** [comment]
HI. 
I'm going to optimize whole build for smaller footprint in the next release. 
If You don't need some futures, e.g auto device detection, it may help. 

Also. You could try to build in release mode. it has significantly smaller binary size.

**Comment by max-bondarenko** [comment]
Minimal size for minimal functional app significantly bigger than 64KB. Mostly because of write() from **stdlib**.
